import { ArrowLeft, Check, LockKeyhole, LogOut, Sparkles } from "lucide-react";
import type { User } from "@supabase/supabase-js";
import { hasPermanentPremiumAccess } from "@/lib/premiumAccess";

type PremiumRoomProps = { user: User; isPremium: boolean; onBack: () => void; onPricing: () => void; onSignOut: () => Promise<void> };

export default function PremiumRoom({ user, isPremium, onBack, onPricing, onSignOut }: PremiumRoomProps) {
  return <div className="premium-room-shell"><header className="profile-topbar"><a className="brand" href="#premium" onClick={(event) => { event.preventDefault(); onBack(); }}><span className="brand-mark"><span className="signal-mark"><span /><span /><span /></span></span><span><strong>eliminator</strong><em>premium</em></span></a><div className="profile-topbar__actions"><button className="profile-link" onClick={onBack}><ArrowLeft size={15} /> Back to feed</button><button className="profile-link profile-link--muted" onClick={onSignOut}><LogOut size={15} /> Sign out</button></div></header><main className="premium-room-layout">{isPremium ? <section className="premium-room-card premium-room-card--active"><span className="premium-room-icon"><Sparkles size={24} /></span><span className="eyebrow eyebrow--red">PREMIUM ACCESS ACTIVE</span><h1>Your premium<br /><i>signal is live.</i></h1><p>Welcome, {user.user_metadata?.full_name || user.email?.split("@")[0] || "member"}. {hasPermanentPremiumAccess(user.email) ? "Your owner account has permanent Premium access." : "This room is available because an approved administrator activated your entitlement."}</p><div className="premium-benefits"><span><Check size={16} /> Premium account status confirmed</span><span><Check size={16} /> Future premium playback tools unlock here</span><span><Check size={16} /> Support remains available through WhatsApp</span></div></section> : <section className="premium-room-card"><span className="premium-room-icon premium-room-icon--locked"><LockKeyhole size={24} /></span><span className="eyebrow eyebrow--red">PREMIUM ACCESS REQUIRED</span><h1>This room is<br /><i>locked for now.</i></h1><p>Your account has not been activated by an approved administrator yet. Contact the Eliminator team on WhatsApp, then return after your Customer ID has been verified.</p><button className="red-button" onClick={onPricing}>Request Premium access <Sparkles size={16} /></button></section>}</main></div>;
}
